'use client'

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Auth0Provider } from '@auth0/auth0-react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const onRedirectCallback = (appState: any) => {
    location.href = (
      appState && appState.returnTo ? appState.returnTo : window.location.pathname
    );
  };
  return (
    <Auth0Provider
      domain="dev-z1noh6-s.auth0.com"
      clientId="dRyzctMsuzWmUP6IFzEmx7TuJVWi2nEi"
      onRedirectCallback={onRedirectCallback}
      authorizationParams={{
        redirect_uri: window.location.origin,
      }}
    >
      <html lang="kr">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </Auth0Provider>
  );
}
